### ISSUE TITLE
libremap-agent broken in 0.5.0 FFF firmware

### ISSUE THREAD

**Issue by kratz00** [kratz00/firmware#3]
```
/usr/sbin/libremap-agent 
/usr/bin/lua: /usr/sbin/libremap-agent:3: module 'luci.model.uci' not found:
	no field package.preload['luci.model.uci']
	no file './luci/model/uci.lua'
	no file '/usr/share/lua/luci/model/uci.lua'
	no file '/usr/share/lua/luci/model/uci/init.lua'
	no file '/usr/lib/lua/luci/model/uci.lua'
	no file '/usr/lib/lua/luci/model/uci/init.lua'
	no file './luci/model/uci.so'
	no file '/usr/lib/lua/luci/model/uci.so'
	no file '/usr/lib/lua/loadall.so'
	no file './luci.so'
	no file '/usr/lib/lua/luci.so'
	no file '/usr/lib/lua/loadall.so'
stack traceback:
	[C]: in function 'require'
	/usr/sbin/libremap-agent:3: in main chunk
	[C]: ?

```

**Comment by RedDog99** [comment]
Da wir keine Libremap mehr haben, kann der Agent raus.

**Comment by mojoaxel** [comment]
Wir haben schon noch eine [Libremap-Instanz](http://libremap.freifunk-franken.de:5984/libremap-dev/_design/libremap-webui/index.html). Diese holt(e) sich Ihre Daten allerdings direkt aus dem Netmon. Der Agent kann also tatsächlich raus. Alternativ könnte man evtl. ALFRED einbauen, damit auch wir die [ffmap Anwendungen](http://www.nilsschneider.net/2013/02/03/ffmap-tutorial.html) verwenden können.

**Comment by kratz00** [comment]
@RedDog99 I will remove that package including dependencies.
@mojoaxel No new features for the 'legacy' firmware, new features should go in ffff-next :)

**Comment by mojoaxel** [comment]
@kratz00 Where can I report issues and feature-requests for the new firmware ffff-next?

**Comment by kratz00** [comment]
@mojoaxel https://github.com/ffff-next/ffff-next
