### ISSUE TITLE
Why is tunneldigger part of the NanoStation-Loco-M2 firmware?

### ISSUE THREAD

**Issue by kratz00** [kratz00/firmware#4]
Commit https://github.com/FreifunkFranken/firmware/commit/5146e9fbee3120cfca3e48f07367fe644d1abc04 removed that package for all supported bsps at that time. Later on commit https://github.com/FreifunkFranken/firmware/commit/1419a08d5d0c9b37e12a84e8a58f053858c8e934 added support for the NanoStation-Loco-M2, which has *CONFIG_PACKAGE_tunneldigger=y*. Clarify if this bsp really needs this package.

**Comment by RedDog99** [comment]
Nein, wir hatten mal mit Tunneldigger experimentiert. Warum es jetzt raus geflogen ist weiß ich nicht, ist an sich eine spannende Technologie, aber aktuell ist sie nicht im Einsatz.
